### ISSUE TITLE
Conflicts with IndiePub authentication

### ISSUE THREAD

**Issue by karadaisy** [mapkyca/known-oauth2-server#2]
Both plugins use `access_token`, so if IndiePub auth succeeds, and then OAuth2 checks the access token, it throws an exception here https://github.com/mapkyca/KnownOAuth2/blob/master/OAuth2/Main.php#L65

IndiePub just returns false if it couldn't find a user, but that's not great either since it gives the user no idea why it failed. it'd be nice to sort of accumulate error messages e.g. "IndiePub: no matches, OAuth2: no matches"

(This is not causing me any problems, just wanted to make sure to log it)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownOAuth2/issues/2" class="u-in-reply-to"></a>Hmm... thanks for flagging this. Will give it some thought....
